services:
  postgres:
    image: scraper/db
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  node:
    image: scraper/node
    command: node scraper.js
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./scraper.js:/app/scraper.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./test.js:/app/test.js

